name: Build WebDriverAgent IPA

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-13

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Xcode 15.2
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.2'

    - name: Install Carthage
      run: |
        brew install carthage || brew upgrade carthage

    - name: Install Dependencies
      run: |
        git config --global url."https://".insteadOf git://
        carthage bootstrap --platform iOS --cache-builds

    - name: Build for Testing with Custom Bundle ID
      run: |
        xcodebuild build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
          -configuration Release \
          -derivedDataPath ./DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEBUG_INFORMATION_FORMAT=dwarf \
          GCC_SYMBOLS=NO \
          PRODUCT_BUNDLE_IDENTIFIER=com.ruliang.WebDriverAgentRunner

    - name: Create IPA
      run: |
        cd DerivedData/Build/Products/Release-iphonesimulator
        mkdir -p Payload
        cp -r WebDriverAgentRunner-Runner.app Payload/
        zip -r WebDriverAgentRunner-Runner.ipa Payload/

    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        path: DerivedData/Build/Products/Release-iphonesimulator/*.ipa
        if-no-files-found: error
        name: WDA-iOS-Simulator-IPA
