name: Build WDA IPA

on:
  push:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 15.3

    - name: Install dependencies
      run: |
        mkdir -p Resources
        ./Scripts/bootstrap.sh -d

    - name: Build for Testing
      run: |
        xcodebuild build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=16.2' \
          -configuration Release \
          -derivedDataPath DerivedData \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          DEBUG_INFORMATION_FORMAT=dwarf \
          GCC_SYMBOLS=NO \
          PRODUCT_BUNDLE_IDENTIFIER=com.ruliang.WebDriverAgentRunner

    - name: Create IPA
      run: |
        cd DerivedData/Build/Products/Release-iphonesimulator
        mkdir Payload
        cp -r WebDriverAgentRunner-Runner.app Payload/
        zip -r WebDriverAgentRunner-Runner.ipa Payload

    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        path: DerivedData/Build/Products/Release-iphonesimulator/*.ipa
        if-no-files-found: error
